services:
  - type: web
    name: 3dlogistix-voice-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    staticPublishPath: static
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
      - key: VOICE_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/google-creds.json

files:
  - name: google-creds.json
    path: /etc/secrets/google-creds.json

